apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
