apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.global.eurekaServerUrl }}
            - name: SPRING_CLOUD_CONFIG_URI
              value: {{ .Values.global.configServerUrl }}
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/productsdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shop-petrova-postgresql
                  key: postgres-password
          ports:
            - containerPort: {{ .Values.service.port }}
