apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: main
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/blackmirrror/shop-petrova-config
          ports:
            - containerPort: {{ .Values.service.port }}
